inputs:
  os:
    description: "One of the supported platforms: macos, linux, windows"
    required: true
  arch:
    description: "The architecture to build for: x64, arm64"
    required: true
  extension:
    description: "Platform specific extension to build: dmg, deb, exe"
    required: true
runs:
  using: composite
  steps:
    - name: Set up Python for appdmg to be installed
      if: ${{ inputs.os == 'macos' }}
      shell: bash
      run: brew install python-setuptools
    - name: Install dependencies
      shell: cmd
      run: npm ci
    - name: Update build info
      shell: cmd
      if: false
      run: npm run update-build-info
    - name: Run electron-forge
      shell: cmd
      run: npm run make-electron -- --arch=${{ inputs.arch }}
      env:
        WINDOWS_SIGNTOOL_PATH: "C:\\ev_signer_trilium\\ev_signer_trilium.exe"
        WINDOWS_SIGN_WITH_PARAMS: --executable
    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: out/make
