name: Release
on:
  # ! Make sure this is removed before merging.
  push:
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-electron:
    name: Make Electron
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os:
          - name: windows
            image: win-signing
            shell: cmd
            forge_platform: win32
    runs-on: ${{ matrix.os.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up node & dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run the build
        uses: ./.github/actions/build-electron
        with:
          os: ${{ matrix.os.name }}
          arch: ${{ matrix.arch }}
          shell: ${{ matrix.os.shell }}
          forge_platform: ${{ matrix.os.forge_platform }}
        env:
          APPLE_APP_CERTIFICATE_BASE64: ${{ secrets.APPLE_APP_CERTIFICATE_BASE64 }}
          APPLE_APP_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_APP_CERTIFICATE_PASSWORD }}
          APPLE_INSTALLER_CERTIFICATE_BASE64: ${{ secrets.APPLE_INSTALLER_CERTIFICATE_BASE64 }}
          APPLE_INSTALLER_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_INSTALLER_CERTIFICATE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          WINDOWS_SIGN_EXECUTABLE: ${{ vars.WINDOWS_SIGN_EXECUTABLE }}

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-desktop-${{ matrix.os.name }}-${{ matrix.arch }}
          path: upload/*.*

  publish_release:
    name: Publish release
    runs-on: ubuntu-latest
    needs:
      - make-electron
    steps:
      - run: mkdir upload

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: release-*
          path: upload

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 0.0.0 # ! Make sure this is removed before merging.
          draft: false
          make_latest: false # ! Make sure this is removed before merging.
          fail_on_unmatched_files: true
          files: upload/*.*

      - name: Publish to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: TriliumNext.Notes
          token: ${{ secrets.WINGET_PAT }}
