name: Release
on:
  push:
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make-electron:
    name: Make Electron
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64]
        os:
          - name: windows
            image: windows-latest-arm
            shell: cmd
            forge_platform: win32
    runs-on: ${{ matrix.os.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up node & dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Set up signer
        run: |
          cd packages/electron-forge-win-signer
          npm i
          npm run build
      - name: Trigger a fake signing
        run: |
          node packages/electron-forge-win-signer/dist/index.js
